# Preface {.unnumbered}

This material demonstrates how to use [Shiny for Python](https://shiny.posit.co/py/) to implement example applications and solutions for exercises found in Hadley Wickham's book [Mastering Shiny](https://www.oreilly.com/library/view/mastering-shiny/9781492047377/). These exercises were originally implemented in R.

This resource primarily focuses on code examples, with minimal additional details about Shiny for Python itself. It does not provide a comprehensive explantion of the Shiny frame.

To gain a thorough understanding of the Shiny framework, I highly recommend reading Hadley Wickham's [Mastering Shiny](https://www.oreilly.com/library/view/mastering-shiny/9781492047377/). An [online version](https://mastering-shiny.org) is also available.

The following material were referenced while creating this resource:

- [Mastering Shiny](https://mastering-shiny.org) by Hadley Wickham
- [Learn Shiny](https://shiny.posit.co/py/docs/overview.html) by Posit Inc. on Shiny for Python website
- [Shiny R to Python translation guide](https://gist.github.com/wch/616934a6fe57636434154c112ac8a718) by Winston Chang
- [Change Log for Shiny for Python](https://github.com/posit-dev/py-shiny/blob/main/CHANGELOG.md)

I also received valuable assistance from the Shiny community on Discord when I asked questions about implementing several examples. A special thank you to Gordon Shotwell, Joe Cheng, and the entire community for their great help!

Computation environment is as follows:

## Python

### Python version

```{python} 
!python --version
```

### Packages

```{python}
with open('requirements.txt', 'r') as f:
    print(f.read())
```


## IDE

### VS Code extensions

- [Shiny for Python](https://marketplace.visualstudio.com/items?itemName=posit.shiny-python)

